const data ={
    products:[
        {
            _id: '1',
            name: 'FIODIO Membrane Gaming Keyboard',
            category: 'Keyboards',
            image: '/images/p1.jpg',
            price: 50,
            brand: 'FIODIO',
            rating: 1.5,
            numReviews: 414,
            description: 'USB Wired Keyboard with Rainbow Backlit, 104 Comfortable Quiet Silent Keys, 26 Anti-Ghosting Keys, Spill Resistant, Multimedia Control for PC and Desktop Computer',
        },
        {
            _id: '2',
            name: 'Razer Sphex V2 Gaming Mouse Pad',
            category: 'Mouse Pads',
            image: '/images/p2.jpg',
            price: 20,
            brand: 'Razer',
            rating: 4,
            numReviews: 25,
            description: 'Ultra-Thin Form Factor - Optimized Gaming Surface - Polycarbonate Finish',
        },
        {
            _id: '3',
            name: 'Logitech Wireless Mouse',
            category: 'Mouses',
            image: '/images/p3.jpg',
            price: 40,
            brand: 'Logitech',
            rating: 3.5,
            numReviews: 542,
            description: 'Logitech Wireless Mouse M185 (Swift Grey)',
        },
        {
            _id: '4',
            name: 'Gaming Graphics Card',
            category: 'Graphics Cards',
            image: '/images/p4.jpg',
            price: 200,
            brand: 'ASUS',
            rating: 4,
            numReviews: 5184,
            description: 'ASUS GeForce GTX 1050 Ti 4GB Phoenix Fan Edition DVI-D HDMI DP 1.4 Gaming Graphics Card (PH-GTX1050TI-4G) Graphic Cards',
        },
        {
            _id: '5',
            name: 'HP 15 Laptop',
            category: 'Laptops',
            image: '/images/p5.jpg',
            price: 630,
            brand: 'Hp',
            rating: 5,
            numReviews: 512,
            description: 'HP 15 Laptop, 11th Gen Intel Core i5-1135G7 Processor, 8 GB RAM, 256 GB SSD Storage, 15.6” Full HD IPS Display, Windows 10 Home, HP Fast Charge, Lightweight Design (15-dy2021nr, 2020)',
        },
        {
            _id: '6',
            name: 'Kids Headphones',
            category: 'Headphones',
            image: '/images/p6.jpg',
            price: 24,
            brand: 'ELECDER',
            rating: 4.5,
            numReviews: 125,
            description: 'Elecder i37 Kids Headphones Children Girls Boys Teens Foldable Adjustable On Ear Headphones 3.5mm Jack Compatible Cellphones Computer MP3/4 Kindle School Tablet Green/Purple',
        },
        {
            _id: '7',
            name: 'Apple AirPods Pro',
            category: 'Apple',
            image: '/images/p7.jpg',
            price: 70,
            brand: 'Apple',
            rating: 1,
            numReviews: 10,
            description: 'Apple AirPods Pro',
        },
        {
            _id: '8',
            name: 'Desktop Computer',
            category: 'Computers',
            image: '/images/p8.jpg',
            price: 300,
            brand: 'Alarco',
            rating: 2.5,
            numReviews: 158,
            description: 'Alarco Gaming PC Desktop Computer Intel i5 3.10GHz,8GB Ram,1TB Hard Drive,Windows 10 pro,WiFi Ready,Video Card Nvidia GTX 650 1GB, 6 RGB Fans with Remote',
        },
        {
            _id: '9',
            name: 'Monitor',
            category: 'Monitors',
            image: '/images/p9.jpg',
            price: 170,
            brand: 'Acer',
            rating: 2,
            numReviews: 197,
            description: 'Acer SB220Q bi 21.5 Inches Full HD (1920 x 1080) IPS Ultra-Thin Zero Frame Monitor (HDMI & VGA Port), Black',
        },
        {
            _id: '10',
            name: 'Desktop Processor',
            category: 'Processors',
            image: '/images/p10.jpg',
            price: 340,
            brand: 'Intel',
            rating: 2.5,
            numReviews: 345,
            description: 'Intel BX80684I99900KF Intel Core i9-9900KF Desktop Processor 8 Cores up to 5.0 GHz Turbo Unlocked Without Processor Graphics LGA1151 300 Series 95W',
        },

    ]
}

export default data;